/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Member } from "./Member";
import { MemberCountArgs } from "./MemberCountArgs";
import { MemberFindManyArgs } from "./MemberFindManyArgs";
import { MemberFindUniqueArgs } from "./MemberFindUniqueArgs";
import { CreateMemberArgs } from "./CreateMemberArgs";
import { UpdateMemberArgs } from "./UpdateMemberArgs";
import { DeleteMemberArgs } from "./DeleteMemberArgs";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { AttendanceFindManyArgs } from "../../attendance/base/AttendanceFindManyArgs";
import { Attendance } from "../../attendance/base/Attendance";
import { CustomerSupportFindManyArgs } from "../../customerSupport/base/CustomerSupportFindManyArgs";
import { CustomerSupport } from "../../customerSupport/base/CustomerSupport";
import { Membership } from "../../membership/base/Membership";
import { MemberService } from "../member.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Member)
export class MemberResolverBase {
  constructor(
    protected readonly service: MemberService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Member",
    action: "read",
    possession: "any",
  })
  async _membersMeta(
    @graphql.Args() args: MemberCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Member])
  @nestAccessControl.UseRoles({
    resource: "Member",
    action: "read",
    possession: "any",
  })
  async members(@graphql.Args() args: MemberFindManyArgs): Promise<Member[]> {
    return this.service.members(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Member, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Member",
    action: "read",
    possession: "own",
  })
  async member(
    @graphql.Args() args: MemberFindUniqueArgs
  ): Promise<Member | null> {
    const result = await this.service.member(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Member)
  @nestAccessControl.UseRoles({
    resource: "Member",
    action: "create",
    possession: "any",
  })
  async createMember(@graphql.Args() args: CreateMemberArgs): Promise<Member> {
    return await this.service.createMember({
      ...args,
      data: {
        ...args.data,

        membership: args.data.membership
          ? {
              connect: args.data.membership,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Member)
  @nestAccessControl.UseRoles({
    resource: "Member",
    action: "update",
    possession: "any",
  })
  async updateMember(
    @graphql.Args() args: UpdateMemberArgs
  ): Promise<Member | null> {
    try {
      return await this.service.updateMember({
        ...args,
        data: {
          ...args.data,

          membership: args.data.membership
            ? {
                connect: args.data.membership,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Member)
  @nestAccessControl.UseRoles({
    resource: "Member",
    action: "delete",
    possession: "any",
  })
  async deleteMember(
    @graphql.Args() args: DeleteMemberArgs
  ): Promise<Member | null> {
    try {
      return await this.service.deleteMember(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Appointment], { name: "appointments" })
  @nestAccessControl.UseRoles({
    resource: "Appointment",
    action: "read",
    possession: "any",
  })
  async findAppointments(
    @graphql.Parent() parent: Member,
    @graphql.Args() args: AppointmentFindManyArgs
  ): Promise<Appointment[]> {
    const results = await this.service.findAppointments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Attendance], { name: "attendances" })
  @nestAccessControl.UseRoles({
    resource: "Attendance",
    action: "read",
    possession: "any",
  })
  async findAttendances(
    @graphql.Parent() parent: Member,
    @graphql.Args() args: AttendanceFindManyArgs
  ): Promise<Attendance[]> {
    const results = await this.service.findAttendances(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [CustomerSupport], { name: "customerSupports" })
  @nestAccessControl.UseRoles({
    resource: "CustomerSupport",
    action: "read",
    possession: "any",
  })
  async findCustomerSupports(
    @graphql.Parent() parent: Member,
    @graphql.Args() args: CustomerSupportFindManyArgs
  ): Promise<CustomerSupport[]> {
    const results = await this.service.findCustomerSupports(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Membership, {
    nullable: true,
    name: "membership",
  })
  @nestAccessControl.UseRoles({
    resource: "Membership",
    action: "read",
    possession: "any",
  })
  async getMembership(
    @graphql.Parent() parent: Member
  ): Promise<Membership | null> {
    const result = await this.service.getMembership(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
