/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CustomerSupportService } from "../customerSupport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CustomerSupportCreateInput } from "./CustomerSupportCreateInput";
import { CustomerSupport } from "./CustomerSupport";
import { CustomerSupportFindManyArgs } from "./CustomerSupportFindManyArgs";
import { CustomerSupportWhereUniqueInput } from "./CustomerSupportWhereUniqueInput";
import { CustomerSupportUpdateInput } from "./CustomerSupportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CustomerSupportControllerBase {
  constructor(
    protected readonly service: CustomerSupportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerSupport })
  @nestAccessControl.UseRoles({
    resource: "CustomerSupport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCustomerSupport(
    @common.Body() data: CustomerSupportCreateInput
  ): Promise<CustomerSupport> {
    return await this.service.createCustomerSupport({
      data: {
        ...data,

        member: data.member
          ? {
              connect: data.member,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        issue: true,

        member: {
          select: {
            id: true,
          },
        },

        resolution: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerSupport] })
  @ApiNestedQuery(CustomerSupportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerSupport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerSupports(
    @common.Req() request: Request
  ): Promise<CustomerSupport[]> {
    const args = plainToClass(CustomerSupportFindManyArgs, request.query);
    return this.service.customerSupports({
      ...args,
      select: {
        createdAt: true,
        id: true,
        issue: true,

        member: {
          select: {
            id: true,
          },
        },

        resolution: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerSupport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerSupport(
    @common.Param() params: CustomerSupportWhereUniqueInput
  ): Promise<CustomerSupport | null> {
    const result = await this.service.customerSupport({
      where: params,
      select: {
        createdAt: true,
        id: true,
        issue: true,

        member: {
          select: {
            id: true,
          },
        },

        resolution: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerSupport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCustomerSupport(
    @common.Param() params: CustomerSupportWhereUniqueInput,
    @common.Body() data: CustomerSupportUpdateInput
  ): Promise<CustomerSupport | null> {
    try {
      return await this.service.updateCustomerSupport({
        where: params,
        data: {
          ...data,

          member: data.member
            ? {
                connect: data.member,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          issue: true,

          member: {
            select: {
              id: true,
            },
          },

          resolution: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerSupport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCustomerSupport(
    @common.Param() params: CustomerSupportWhereUniqueInput
  ): Promise<CustomerSupport | null> {
    try {
      return await this.service.deleteCustomerSupport({
        where: params,
        select: {
          createdAt: true,
          id: true,
          issue: true,

          member: {
            select: {
              id: true,
            },
          },

          resolution: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
